name: Twitter to Telegram
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run bot
        run: |
          pip install requests
          python << 'PY'
          import requests, re
          BOT="8520671007:AAG-gmwnuvzTWOL_7ZsA1h5KCqetYrDt95A"
          CH="@alha64"
          r=requests.get("https://api.fxtwitter.com/hilalstuff",timeout=20).json()
          txt=r['tweets'][0]['text']
          txt=re.sub(r'https?://\S+','',txt).strip()
          msg=txt+"\n\n@alha64"
          requests.post(f"https://api.telegram.org/bot{BOT}/sendMessage",data={"chat_id":CH,"text":msg})
          print(msg)
          PY
